[package]
name = "ammonia"
version = "2.1.1"
authors = ["Michael Howell <michael@notriddle.com>"]
description = "HTML Sanitization"
keywords = [ "sanitization", "html", "security", "xss" ]
license = "MIT / Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/ammonia/"
repository = "https://github.com/rust-ammonia/ammonia"
categories = [ "web-programming", "text-processing" ]

[dependencies]
html5ever = "0.23"
maplit = "1.0"
matches = "0.1.6"
tendril = "0.4"
url = "1"
lazy_static = "1.3"

[dev-dependencies]
version-sync = "0.8"
